name: tfg
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.2
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_modular: ^6.0.5
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  fonts:
    - family: Oxygen Bold
      fonts:
        - asset: fonts/Oxygen-Bold.ttf
    - family: Oxygen Light
      fonts:
        - asset: fonts/Oxygen-Light.ttf
    - family: Oxygen Regular
      fonts:
        - asset: fonts/Oxygen-Regular.ttf
  assets:
    - images/
  generate: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
